import importlib
import MNRB.MNRB_UI.mnrb_editor as mnrb_editor
import MNRB.MNRB_UI.mnrb_ui_utils as utils
import MNRB.MNRB_UI.mnrb_nodeEditorTab as nodeEditorTab

import MNRB.MNRB_UI.node_Editor_UI.node_Editor_Widget as nodeEditorWidget
import MNRB.MNRB_UI.node_Editor_UI.node_Editor_Serializable as nodeEditorSerializable
import MNRB.MNRB_UI.node_Editor_UI.node_Editor_Scene as nodeEditorScene
import MNRB.MNRB_UI.node_Editor_UI.node_Editor_Node as nodeEditorNode
import MNRB.MNRB_UI.node_Editor_UI.node_Editor_Socket as nodeEditorSocket
import MNRB.MNRB_UI.node_Editor_UI.node_Editor_Edge as nodeEditorEdge
import MNRB.MNRB_UI.node_Editor_UI.node_Editor_DragEdge as NodeEditorDragEdge
import MNRB.MNRB_UI.node_Editor_UI.node_Editor_Cutline as NodeEditorCutline
import MNRB.MNRB_UI.node_Editor_UI.node_Editor_SceneHistory as NodeEditorSceneHistory
import MNRB.MNRB_UI.node_Editor_UI.node_Editor_Clipboard as NodeEditorSceneClipboard
import MNRB.MNRB_UI.node_Editor_UI.node_Editor_DragNodeList as NodeEditorDragNodeList
import MNRB.MNRB_UI.node_Editor_UI.node_Editor_PropertiesWidget as NodeEditorPropertiesWidget
import MNRB.MNRB_UI.node_Editor_UI.node_Editor_NodeProperties as NodeEditorNodeProperties
import MNRB.MNRB_UI.node_Editor_UI.node_Editor_SceneProperties as NodeEditorSceneProperties
import MNRB.MNRB_UI.node_Editor_UI.node_Editor_EdgeProperties as NodeEditorEdgeProperties
import MNRB.MNRB_UI.node_Editor_conf as NodeEditorConf 
import MNRB.MNRB_UI.MNRB_Nodes.mnrb_node_base as MNRBNodeBase

import MNRB.MNRB_UI.node_Editor_GraphicComponents.node_Editor_QGraphicScene as nodeEditorGraphicsScene
import MNRB.MNRB_UI.node_Editor_GraphicComponents.node_Editor_QGraphicView as nodeEditorGraphicsView
import MNRB.MNRB_UI.node_Editor_GraphicComponents.node_Editor_QGraphicNode as nodeEditorGraphicsNode
import MNRB.MNRB_UI.node_Editor_GraphicComponents.node_Editor_QGraphicContent as nodeEditorGraphicContent
import MNRB.MNRB_UI.node_Editor_GraphicComponents.node_Editor_QGraphicSocket as nodeEditorGraphicSocket 
import MNRB.MNRB_UI.node_Editor_GraphicComponents.node_Editor_QGraphicEdgePath as nodeEditorGraphicEdgePath
import MNRB.MNRB_UI.node_Editor_GraphicComponents.node_Editor_QGraphicEdge as nodeEditorGraphicEdge

import MNRB.MNRB_UI.node_Editor_Exceptions.node_Editor_FileException as nodeEditorInvalidFile

importlib.reload(mnrb_editor)
importlib.reload(utils)
importlib.reload(nodeEditorTab)

importlib.reload(nodeEditorWidget)
importlib.reload(nodeEditorSerializable)
importlib.reload(nodeEditorScene)
importlib.reload(nodeEditorNode)
importlib.reload(nodeEditorSocket)
importlib.reload(nodeEditorEdge)
importlib.reload(NodeEditorDragEdge)
importlib.reload(NodeEditorCutline)
importlib.reload(NodeEditorSceneHistory)
importlib.reload(NodeEditorSceneClipboard)
importlib.reload(NodeEditorDragNodeList)
importlib.reload(NodeEditorPropertiesWidget)
importlib.reload(NodeEditorNodeProperties)
importlib.reload(NodeEditorSceneProperties)
importlib.reload(NodeEditorEdgeProperties)
importlib.reload(NodeEditorConf)
importlib.reload(MNRBNodeBase)

importlib.reload(nodeEditorGraphicsScene)
importlib.reload(nodeEditorGraphicsView)
importlib.reload(nodeEditorGraphicsNode)
importlib.reload(nodeEditorGraphicContent)
importlib.reload(nodeEditorGraphicSocket)
importlib.reload(nodeEditorGraphicEdgePath)
importlib.reload(nodeEditorGraphicEdge)

importlib.reload(nodeEditorInvalidFile)

newEditor = mnrb_editor.mnrb_Editor()

newEditor.show()